# ===========================================
# Information Settings
# ===========================================

#navigation
menu: 
  article: /
  archives: /archives
  tags: /tags
  about: /about
  # RSS: /atom.xml

# favicon
favicon: /images/favicon.png 

# ===========================================
# Color&Schemes Setting
# ===========================================

## Common

# Mobile-Header
# light | dark
mobile-header: light

# Scheme
# banderole | balance
scheme: banderole

## Banderole
# Header Style
# line | block
header-style: block

# Article Header Sign
header_sign: §

# theme-style
# miku | sakura | dark | green | blue | purple
theme-style: miku

# ===========================================
# Article Setting
# ===========================================

# Navigator in post
toc: true

# Use copyright infomation
copyright:
  enable: true
  license: ''

#Reword button or message(fill your QRCode of any Pay.)
reward: 
  enable: false
  alipay: /images/alipay_reward.jpg
  wechat: /images/wechatpay_reward.jpg

# ===========================================
# Social Contact
# ===========================================

# Comments // Please only switch one on.
comments: 
  enable: true
  changyan:
    appid: cytisK3gN
    appkey: prod_7df35a33a6a4460b19937682198c07e7

  # disqus: 

  # changyan:
  #   appid: 
  #   appkey: 

  # gitment:
  #   owner:
  #   repo:
  #   client_id:
  #   client_secret:

# sub //Please just fill out ID.
#sub:
#  facebook: 1
#  twitter: 2
#  instagram: 3
#  weibo: 4
#  zhihu: 5
#  github: 6
#  linkedin: 7

#Friend link
# friendLink: 

# ===========================================
# Analytics
# ===========================================

analytics:
  baidu: 853529895bee96b6d4b73302b1450327

#visit_count(Powered by busuanzi on http://busuanzi.ibruce.info/)
visit_count: false

# ===========================================
# Theme Settings
# ===========================================

# mathjax
mathjax: true

# lightbox
lightbox: true

# animate (Powered by Syuanpi on https://colmugx.github.io/Syuanpi.css)
animate: true

# Created Time
since: 2016

# plugin
# plugins:

# about
# self:  

# ===========================================
# Search Settings
# ===========================================

# Search 
search: true

greetings:
  morning: '我的博客里可没有早饭！'
  noon: '记得午休吃饭，不着急看我的博客~'
  after: '下午好，感谢查阅我的博客'
  night: '您来我的博客看笑话当做休息嘛'
  midnight: '我觉得大半夜就不要看啦'

# ===========================================
# Documents Styles
# ===========================================

# article-fonts
# default | Simsun | YaHei | Hel | Custom
fonts-style: default

# code-fonts
# default | Custom
code-style: default

# ===========================================
# WebApp Settings (iOS)
# ===========================================


# ===========================================
# Version
# ===========================================
version: 2.1

